### ISSUE TITLE
Elaborar entrevista

### ISSUE THREAD

**Issue by lucasA27** [Requisitos-de-Software/2019.2-Waze#14]
# Elaborar entrevista

## Descrição da Issue
A entrevista é uma técnica tradicional e simples que pode produzir bons resultados no contexto de elicitação de requisitos.

### Tarefas:
- [x] Introdução
- [x] Metodologia
- [x] Entrevista

**Comment by RCristyan** [comment]
A entrevista foi concluída e obtivemos dados importantes para o projeto.
