### ISSUE TITLE
História de usuário

### ISSUE THREAD

**Issue by jpcirqueira** [Requisitos-de-Software/2019.2-Waze#33]
# História de usuário

**Comment by RCristyan** [comment]
É importante observar que no momento temos dois documentos que foram desenvolvidos simultâneamente: UserStories.md e UserHist.md
Vamos precisar juntar os dois documentos em um só para evitar ambiguidades, além de modificar alguns IDs de histórias de usuário e verificar se os rastros não foram prejudicados.
